spring.application.name=code_clash

spring.datasource.url=jdbc:postgresql://localhost:5432/code_clash
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.github.client-id=${GIT_HUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GIT_HUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email


judge0.base-url=https://ce.judge0.comhttps://ce.judge0.comhttps://ce.judge0.com
judge0.api-key=024815ec97mshbc54e1feec1ab9fp10026djsn1cf372df3a61
